### ISSUE TITLE
Q: Release cycle

### ISSUE THREAD

**Issue by ogunkarakus** [LeShadow/ArtisanExtended#4]
Hi,

Can you tag any changes made today? I'll try to add the #1 and #2 features.

Best regards, Ogün Karakuş

**Comment by LeShadow** [comment]
@ogunkarakus I did  #1 already :/. Should push them tomorrow.
And #2 is almost ready. 

Good for you?

**Comment by ogunkarakus** [comment]
@LeShadow :+1: Have anything I can do?

**Comment by LeShadow** [comment]
@ogunkarakus got any other ideas for this extension? Uploaded the code, if you want, you can test the two new commands.

**Comment by ogunkarakus** [comment]
Hi,

Can you tag changes?

Best regards, Ogün Karakuş

**Comment by LeShadow** [comment]
Hi @ogunkarakus ,

I'll make some additional changes tonight. If i'm satisfied with the result of them, i'll bring out a new release.

**Comment by ogunkarakus** [comment]
@LeShadow :+1:
